Creacion bases usuarios
4GeeksAcademy/app_gestion_gym_crossfit_proyecto_final_pt28 pull request #4
Opened 2024-05-13 18:03 UTC by rafaelnavam

se crearon enpoint CRUD para user master, normal user, CRUD de creacion de clases, booking class, delete booking, landing page

2024-05-13 18:38 UTC, rafaelnavam commented
confirmar

2024-05-14 03:20 UTC, valeriaasalcedoo requested changes
hay que tomar en cuenta los cambios que nos comento david

2024-05-14 03:21 UTC, valeriaasalcedoo approved these changes

2024-05-14 03:23 UTC, valeriaasalcedoo approved these changes

2024-05-14 03:25 UTC, valeriaasalcedoo approved these changes

2024-05-14 03:25 UTC, valeriaasalcedoo approved these changes

2024-05-14 03:26 UTC, valeriaasalcedoo approved these changes

2024-05-14 03:34 UTC, valeriaasalcedoo approved these changes

2024-05-14 03:36 UTC, rafaelnavam commented
porfavor haz pulllllllllll

2024-05-14 03:44 UTC, closed without merging